/**:
  ublox_rover:
    ros__parameters:
      debug: 1                   # Range 0-4 (0 means no debug statements will print)

      #save:
      #  mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver 
                                  # Manager, Antenna, and Logging Configuration
      gnss:
        gps: true
        glonass: true
        galileo: true
        beidu: true
        qzss: true
        sbas: true

      device: /dev/ttyACM0
      frame_id: gps
      rate: 10.0                    # in Hz
      nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may 
                                  # be either 5 Hz (Dual constellation) or 
                                  # 8 Hz (GPS only)
      dynamic_model: airborne2    # Airborne < 2G, 2D fix not supported (3D only), 
                                  # Max Alt: 50km
                                  # Max Horizontal Velocity: 250 m/s, 
                                  # Max Vertical Velocity: 100 m/s
      fix_mode: auto
      enable_ppp: false           # Not supported by C94-M8P
      dr_limit: 0

      usb:
        in: 35                     # UBX + NMEA | RTCM3 is disabled as it should come from UART
        out: 1                    # UBX

      uart1:
        baudrate: 460800
        in: 32                    # RTCM3
        out: 0                    # No output

      dgnss_mode: 3               # Fixed mode

      inf: 
        all: true                 # Whether to display all INF messages in console

      # Enable u-blox message publishers
      publish:
        aid:
          hui: false

        nav:
          posecef: false
          relposned: false
          heading: false

        rxm:
          rtcm: true

      tmode3: 0

  # ublox_mbase:
  #   ros__parameters:
  #     debug: 1                   # Range 0-4 (0 means no debug statements will print)

  #     #save:
  #     #  mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver 
  #                                 # Manager, Antenna, and Logging Configuration
  #     gnss:
  #       gps: true
  #       glonass: true
  #       galileo: true
  #       beidu: false
  #       qzss: false
  #       sbas: false
      
  #     # nmea:
  #     #   set: true
  #     #   version: 4

  #     device: /dev/ttyACM1
  #     frame_id: gps_mbase
  #     rate: 10.0                     # in Hz
  #     nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may 
  #                                 # be either 5 Hz (Dual constellation) or 
  #                                 # 8 Hz (GPS only)
  #     dynamic_model: airborne2    # Airborne < 2G, 2D fix not supported (3D only), 
  #                                 # Max Alt: 50km
  #                                 # Max Horizontal Velocity: 250 m/s, 
  #                                 # Max Vertical Velocity: 100 m/s
  #     fix_mode: auto
  #     enable_ppp: false           # Not supported by C94-M8P
  #     dr_limit: 0

  #     usb:
  #       in: 35
  #       out: 1

  #     uart1:
  #       baudrate: 460800
  #       in: 0                      # No Input on UART
  #       out: 32                    # RTCM 3

  #     dgnss_mode: 3               # Fixed mode

  #     inf: 
  #       all: true                 # Whether to display all INF messages in console

  #     # Enable u-blox message publishers
  #     publish:
  #       aid:
  #         hui: false

  #       nav:
  #         posecef: false
  #         relposned: false
  #         heading: true

  #       rxm:
  #         rtcm: true

  #     tmode3: 0
